### ISSUE TITLE
Stack Trace not relevant

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [adonisjs/require-ts#2] opened 2020-10-20 14:08 UTC
## Package version
@adonisjs/require-ts: 1.0.4

## Node.js and npm version
Node: 12.18.2
Npm: 6.14.5

## Problem
Actually, if i got an Syntax Error the stack trace send this in my console (for example):
```
[ info ]  building project...
[ info ]  starting http server...

SyntaxError: Unexpected token '.'


1 Module._compile
  C:\project\node_modules\pirates\lib\index.js:99

2 Object.newLoader [as .ts]
  C:\project\node_modules\pirates\lib\index.js:104

3 anonymous
  C:\project\node_modules\require-all\index.js:56

[ warn ]  Underlying HTTP server died with "0 code"
[ info ]  shutting down
```

Its really hard to debug with this style of error ...

**Comment by thetutlage** [comment] 2020-10-20 15:25
What's the code that has this syntax error?

**Comment by Sebastien-Ahkrin** [comment] 2020-10-21 09:52
```js
return mod._compile(newCode, filename);
```

in node_modules\pirates\lib\index.js:104

**Comment by thetutlage** [comment] 2020-10-21 09:57
I mean your code that has the syntax error. I need it to reproduce the issue

**Comment by targos** [comment] 2020-10-21 12:26
For example in `start/routes.ts`, use some optional chaining (not available in Node.js 12):

```ts
import Route from '@ioc:Adonis/Core/Route';

Route?.get('/', async () => { return 'hello world' });
```

```
> node ace serve --watch
[ info ]  building project...
[ info ]  starting http server...

SyntaxError: Unexpected token '.'


1 Module._compile
  D:\Git\project\node_modules\pirates\lib\index.js:99

2 Object.newLoader [as .ts]
  D:\Git\project\node_modules\pirates\lib\index.js:104

3 Application.resolveModule
  D:\Git\project\node_modules\@adonisjs\application\build\src\Application.js:116

[ warn ]  Underlying HTTP server died with "0 code"
[ info ]  shutting down
```

**Comment by Sebastien-Ahkrin** [comment] 2020-10-21 12:27
> 
> 
> For example in `start/routes.ts`, use some optional chaining (not available in Node.js 12):
> 
> ```ts
> import Route from '@ioc:Adonis/Core/Route';
> 
> Route?.get('/', async () => { return 'hello world' });
> ```
> 
> ```
> > node ace serve --watch
> [ info ]  building project...
> [ info ]  starting http server...
> 
> SyntaxError: Unexpected token '.'
> 
> 
> 1 Module._compile
>   D:\Git\project\node_modules\pirates\lib\index.js:99
> 
> 2 Object.newLoader [as .ts]
>   D:\Git\project\node_modules\pirates\lib\index.js:104
> 
> 3 Application.resolveModule
>   D:\Git\project\node_modules\@adonisjs\application\build\src\Application.js:116
> 
> [ warn ]  Underlying HTTP server died with "0 code"
> [ info ]  shutting down
> ```

Thanks @targos ^^

**Comment by thetutlage** [comment] 2020-10-22 03:26
It returns the same output as running the Javascript code directly. Here is a repo to reproduce it https://github.com/thetutlage/require-ts-issue-2

**Comment by targos** [comment] 2020-10-22 06:19
You're right, but it doesn't actually show the issue, it rather shows the expected behavior :)
In both JS and TS examples in https://github.com/thetutlage/require-ts-issue-2, the output contains the name of the file that has the error and the part of the code that triggered it:

```
D:\Git\forks\require-ts-issue-2\foo.ts:5
foo?.bar();
    ^

SyntaxError: Unexpected token '.'
```

In the example executed in Adonis, the output only has the error message, which makes it very difficult to know where the error comes from (especially with optional chaining because `Unexpected token '.'` is not obviously related to that).

```
[ info ]  starting http server...

SyntaxError: Unexpected token '.'


1 Module._compile
  D:\Git\project\node_modules\pirates\lib\index.js:99
```

**Comment by thetutlage** [comment] 2020-10-22 06:22
Ahhh, that means it is getting swallowed somewhere at the AdonisJS assembler level. My intent was narrow down that the issue doesn't belong to this repo

**Comment by thetutlage** [comment] 2020-10-22 06:32
I got it. The error is coming from `youch` ( the one that shows the pretty errors on terminal ). If you uninstall youch and youch terminal then the error will contain the filename too.

Have to fix there

**Comment by thetutlage** [comment] 2020-10-22 06:34
Narrowed down a bit more. Youch uses [stack-trace](https://npm.im/stack-trace) package and here is the [exact issue](https://github.com/felixge/node-stack-trace/issues/29) with that library. I see it is not maintained actively, so we may have to switch to a better alternative or if someone can fork that repo and provide a fix?

**Comment by targos** [comment] 2020-10-22 06:43
Is `youch` maintained? Could we contribute to it?

**Comment by thetutlage** [comment] 2020-10-22 06:56
Yes. It is actively maintained and feel free to contribute :)

**Comment by targos** [comment] 2020-10-22 06:59
This module seems interesting: https://github.com/xpl/stacktracey

In your repo:
```js
const StackTracey = require('stacktracey');

try {
  require('./index.js')
} catch (e) {
  const stack = new StackTracey (e)
  console.log(stack)
}
```

The first item contains info about the syntax error:
```
StackTracey {
  items: [
    {
      file: 'D:/Git/forks/require-ts-issue-2/index.js',
      line: '5',
      column: 5,
      sourceLine: 'foo?.bar()',
      callee: '(syntax error)',
      syntaxError: true
    },
    {
      beforeParse: 'at wrapSafe (internal/modules/cjs/loader.js:931:16)',
      callee: 'wrapSafe',
      index: false,
      native: false,
      file: 'internal/modules/cjs/loader.js',
...
```

**Comment by thetutlage** [comment] 2020-10-22 07:04
Yeah, looks nice. Can you create a PR to swap the modules and ensure there are no breaking changes, since I know a lot of modules (except AdonisJS) relies on youch?

**Comment by targos** [comment] 2020-10-22 07:13
Ah, but in youch, you expose the StackFrame objects. It would be a breaking change to use another library.

**Comment by thetutlage** [comment] 2020-10-22 07:54
If we go with a breaking change. Do you know how different the object properties are? Maybe we can start with a PR and then discuss it further in the youch repo

**Comment by targos** [comment] 2020-10-23 08:56
Unfortunately I do not have the time to work on this for now.

**Comment by thetutlage** [comment] 2020-10-23 09:13
No worries. I will look into it :)

**Comment by targos** [comment] 2020-12-22 09:24
This is still relevant, I think

**Comment by thetutlage** [comment] 2021-02-06 09:02
Closing. Will fix inside youch. I am going to work on it

**Closed as completed by thetutlage** 2021-02-06 09:02 UTC

**Comment by thetutlage** [comment] 2021-12-17 09:12
Fixed in https://github.com/poppinss/youch/commit/0e2bad72e63d6f056873f9b07c2de3decee15441
